trigger: none

pool:
  vmImage: 'ubuntu-latest'
variables:
  azureSubscription: 'HaoSubscriptionConn'      # your Azure DevOps service connection


steps:
- task: AzureCLI@2
  displayName: 'Terraform Init and Plan'
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform version
