# values.yaml
prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
  

grafana:
  adminUser: admin
  adminPassword: admin 
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana/"
