prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
  
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: ingress-nginx
    hosts:
      - prometheus.${ip}.nip.io
    paths:
      - /
    pathType: Prefix


grafana:
  adminUser: admin
  adminPassword: admin
  
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: ingress-nginx
    hosts:
      - grafana.${ip}.nip.io
    paths:
      - /
    pathType: Prefix
